/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "cyan-core": "#06b6d4",
        "emerald-soul": "#10b981",
        "void-stark": "#020617",
        "gold-sovereign": "#ffd700",
        "glass-surface": "rgba(15, 23, 42, 0.6)",
        "glass-frosted": "rgba(255, 255, 255, 0.05)",
        "secondary-container": "#e3e2e1",
        "surface": "#f9f9f8",
        "surface-variant": "#e2e2e2",
        "on-tertiary-fixed-variant": "#5b4310",
        "inverse-on-surface": "#f1f1f0",
        "surface-container-highest": "#e2e2e2",
        "tertiary-container": "#271900",
        "primary-container": "#1c1b1b",
        "secondary-fixed-dim": "#c7c6c5",
        "on-background": "#1a1c1c",
        "on-tertiary-fixed": "#271900",
        "tertiary-fixed": "#ffdea7",
        "surface-container-lowest": "#ffffff",
        "primary": "#000000",
        "inverse-primary": "#c8c6c5",
        "background": "#f9f9f8",
        "on-primary-fixed-variant": "#474646",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f4f3",
        "on-primary-container": "#858383",
        "on-surface-variant": "#444748",
        "primary-fixed-dim": "#c8c6c5",
        "outline-variant": "#c4c7c7",
        "on-secondary-container": "#646464",
        "surface-container": "#eeeeed",
        "surface-dim": "#dadad9",
        "on-error": "#ffffff",
        "surface-tint": "#5f5e5e",
        "outline": "#747878",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#e5c283",
        "inverse-surface": "#2f3130",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#1c1b1b",
        "secondary-fixed": "#e3e2e1",
        "error-container": "#ffdad6",
        "tertiary": "#000000",
        "on-surface": "#1a1c1c",
        "on-secondary-fixed": "#1b1c1b",
        "primary-fixed": "#e5e2e1",
        "surface-container-high": "#e8e8e7",
        "on-tertiary-container": "#9e7f47",
        "surface-bright": "#f9f9f8",
        "on-secondary-fixed-variant": "#464746",
        "secondary": "#5e5e5e",
        "wangdao-red": "#9E1B21",
        "classic-gold": "#C5A059"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-tablet": "32px",
        "margin-mobile": "20px",
        "base": "8px",
        "gutter": "32px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "section-padding": "120px",
        "block-margin": "80px"
      },
      fontFamily: {
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Newsreader", "serif"],
        "headline-lg-mobile": ["Newsreader", "serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Newsreader", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Newsreader", "serif"],
        "display-calligraphy": ["Newsreader", "serif"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "400"}],
        "headline-lg-mobile": ["36px", {"lineHeight": "44px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "300"}],
        "display-calligraphy": ["80px", {"lineHeight": "90px", "letterSpacing": "-0.03em", "fontWeight": "200"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};
