name: AI PR Review
on:
  pull_request:
    types: [ opened, synchronize, edited, reopened, ready_for_review ]
permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: read
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run AI PR Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AI_API_BASE: ${{ vars.AI_API_BASE || secrets.AI_API_BASE }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          AI_MODEL: ${{ vars.AI_MODEL || secrets.AI_MODEL }}
        run: node .github/scripts/pr_review.mjs