name: Auto Rebase AI PRs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Rebase labeled PRs
        uses: cirrus-actions/rebase@1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: "rebase:bot"